spring:
  application:
    name: client
  cloud:
    circuitbreaker:
      hystrix:
        enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
server:
  port: 10002
feign:
  client:
    config:
      # default表示，全局配置，单个配置使用feign的value值代替default
      default:
        connectTimeout: 5000
        readTimeout: 5000

# hystrix的信息访问路径
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
# 配置Hystrix的超时时间，默认1000毫秒，应该比上面两个超时时间加依赖要长
hystrix:
  command:
    # default表示，全局配置，单个配置使用feign的value值代替default
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
# Feign日志
logging.level.com.lp.client.UserClient: debug

#debug: true
